### PR TITLE
re architect, update README, add test, add travis

### PR DESCRIPTION
**Pull request by quanvo87**

### CODE REVIEW

**Comment by quanvo87** [comment]
should the requirements be "xcode 8 or 9"?

**Comment by dingwilson** [comment]
I don't think Xcode version matters tbh. As long as it is Swift 4 toolchain, which can be installed with both Xcode 8 and 9.

**Comment by quanvo87** [comment]
i did that shared scheme thing in one of my commits

i noticed that now in the PR there's

GroupWork.xcodeproj/xcshareddata/xcschemes/GroupWork 2.xcscheme

and

GroupWork.xcodeproj/xcshareddata/xcschemes/GroupWork.xcscheme

i wonder if that's messing anything up

**Comment by quanvo87** [comment]
also if it's complicating things, we can just test on the latest xcode

**Comment by quanvo87** [comment]
we dont have to worry about 4s

**Comment by dingwilson** [comment]
oh oops, I didn't realize you already did that.. I'll remove the duplicated xcscheme. I'm only testing off of GroupWork.xcscheme.

I had to switch to Xcode9.x due to Xcode8.0 travis image not having iOS 11.

Also, I don't think it is iPhone 4s that is failing... It might be iOS 8. The device shouldn't really matter. I'll test against a newer iOS 8 device and see if it still fails.

**Comment by dingwilson** [comment]
Sorry for all the spam. I hate initial travis setup, because it always fails for one reason or another. Can't wait to fix, rebase, and be done with travis haha.

**Comment by quanvo87** [comment]
it's fine haha. it sucks that travis is still slow with swift. my node travis projects build almost immediately lol

**Comment by dingwilson** [comment]
🎉 all tests pass. Successfully testing iOS 8-11.

**Comment by quanvo87** [comment]
sick work on the travis.

i added badges, and other stuff to the README. if everything passes your review, i think this is a good stopping point to put out another release on cocoapods. i want to test it as a dependency.

in order to do that, do we update the podspec to say 0.0.3? or do we merge and release 0.0.3 on github first?

**Comment by dingwilson** [comment]
Thanks! 👍 LGTM

You should be able to do it in either order, as long as you tag/release before you push the podspec.

I would suggest first modifying/committing podspec to 0.0.3, then tagging/releasing 0.0.3, then running `pod trunk push`. This way, you don't have an extra commit after the 0.0.3 tag where you modified the podspec. (extra commit: tag/release 0.0.3, then modify podspec, then run `pod trunk push`)

idk if that makes sense haha

**Pull request merged**
